adding charts for security context fixes

diff --git a/charts/kubeslice-worker-egs/templates/kubeslice-postdelete-hook.yaml b/charts/kubeslice-worker-egs/templates/kubeslice-postdelete-hook.yaml
--- a/charts/kubeslice-worker-egs/templates/kubeslice-postdelete-hook.yaml
+++ b/charts/kubeslice-worker-egs/templates/kubeslice-postdelete-hook.yaml
@@ -85,20 +85,23 @@ metadata:
     "helm.sh/hook-weight": "1"
 data:
   kubeslice-cleanup.sh: |-
-    #!/usr/bin/env bash
-    NAMESPACES=(spire kubeslice-system)
-    for ns in ${NAMESPACES[@]}
-    do
+    #!/bin/sh
+    NAMESPACES="spire kubeslice-system"
+    for ns in $NAMESPACES; do
       kubectl get ns $ns -o name  
-      if [[ $? -eq 1 ]]; then
+      if [ $? -eq 1 ]; then
           echo "$ns namespace was deleted successfully"
           continue
       fi
       echo "finding and removing spiffeids in namespace $ns ..."
-      for item in $(kubectl get clusterspiffeids.spire.spiffe.io -n $ns -o name); do
+      for item in $(kubectl get clusterspiffeids.spire.spiffe.io -n $ns -o name 2>/dev/null); do
         echo "removing item $item"
-        kubectl patch $item -p '{"metadata":{"finalizers":null}}' --type=merge -n $ns
-        kubectl delete $item --ignore-not-found -n $ns
+        kubectl patch "$item" -p '{"metadata":{"finalizers":null}}' --type=merge -n "$ns"
+        if [ $? -eq 0 ]; then
+          kubectl delete "$item" --ignore-not-found -n "$ns"
+        else
+          echo "Failed to patch $item, skipping deletion"
+        fi
       done
     done
     echo "Deleting services from kubeslice-system namespace"
@@ -128,9 +131,9 @@ spec:
       serviceAccountName: kubeslice-postdelete-job
       containers:
         - name: kubectl
-          image: "{{ .Values.global.imageRegistry }}/alpine-k8s:1.22.9"
+          image: "{{ .Values.global.imageRegistry }}/{{ .Values.alpine.image }}:{{ .Values.alpine.tag }}"
           command:
-            - /bin/bash
+            - /bin/sh
             - /tmp/kubeslice-cleanup.sh
           volumeMounts:
             - mountPath: /tmp
@@ -140,3 +143,7 @@ spec:
           configMap:
             name: kubeslice-postdelete-job
       restartPolicy: OnFailure
+      {{- if .Values.imagePullSecretsName }}
+      imagePullSecrets:
+        - name: {{ .Values.imagePullSecretsName }}
+      {{- end }}
